name: Run Python Script

on:
  schedule:
    # Runs every Sunday at 03:00 AM UTC
    - cron: "0 3 * * 0"
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 supabase requests datetime uuid

      # Step 4: Run the Python script
      - name: Run Python script
        run: |
          python your_script.py
